// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfiRS-ENnHr7SRnRQ-UyQAVyRtRfkt36o',
    appId: '1:1045914929951:android:a78876ff4ff2e799417e2a',
    messagingSenderId: '1045914929951',
    projectId: 'movihub-3f0d1',
    storageBucket: 'movihub-3f0d1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaigiFGDinYgvAIQn3GdoCpmmtB_nz4vc',
    appId: '1:1045914929951:web:e8e580110d9e253e417e2a',
    messagingSenderId: '1045914929951',
    projectId: 'movihub-3f0d1',
    authDomain: 'movihub-3f0d1.firebaseapp.com',
    storageBucket: 'movihub-3f0d1.firebasestorage.app',
    measurementId: 'G-HXSB8YZ4GS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaigiFGDinYgvAIQn3GdoCpmmtB_nz4vc',
    appId: '1:1045914929951:web:51852de4b715f3df417e2a',
    messagingSenderId: '1045914929951',
    projectId: 'movihub-3f0d1',
    authDomain: 'movihub-3f0d1.firebaseapp.com',
    storageBucket: 'movihub-3f0d1.firebasestorage.app',
    measurementId: 'G-JS4KPTGE6R',
  );

}